version: '3.8'

services:
  markitdown-api:
    build: .
    container_name: markitdown-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # 可选：挂载本地目录用于测试
      - ./test_files:/app/test_files:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: markitdown-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - markitdown-api
    restart: unless-stopped
    profiles:
      - with-nginx
