[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "markitdown-api"
version = "0.1.0"
description = "HTTP API server for MarkItDown document conversion"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    {name = "Microsoft", email = "autogen@microsoft.com"},
]
keywords = ["markdown", "document", "conversion", "api", "pdf", "llm"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "markitdown>=0.1.0",
    "flask>=2.3.0",
    "flask-cors>=4.0.0",
    "gunicorn>=21.0.0",
    "werkzeug>=2.3.0",
]

[project.optional-dependencies]
fastapi = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "requests>=2.31.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]

[project.urls]
"Homepage" = "https://github.com/microsoft/markitdown"
"Repository" = "https://github.com/microsoft/markitdown"
"Issues" = "https://github.com/microsoft/markitdown/issues"

[project.scripts]
markitdown-api = "markitdown_api.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src/markitdown_api"]

[tool.hatch.version]
path = "src/markitdown_api/__about__.py"

[tool.black]
target-version = ["py310"]
line-length = 88

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
